name: 'medicare_lds_connector'
version: '0.1.1'
config-version: 2

profile: default     

dbt-cloud:
    project-id: 395957

vars:
  input_database: tuva-lds
  input_schema:  raw_files

  claims_enabled: true

  # Default values for data marts, update as needed
  cms_hcc_payment_year: 2021
  quality_measures_period_end: "2020-12-31"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
